create table machine (

  id   bigint              generated by default AS IDENTITY,
  type smallint not null default 0,
  buy_day date not null,
  mac_address varchar(48) not null unique,

  primary key (id)
);