create table client_trace (
  id bigint generated by default as identity,
  trace_on timestamp with time zone default now(),
  deleted boolean default false,
  client_id integer not null,
  name text,
  slug text,
  created_on timestamp,
  version integer,
  primary key(id)
);