create table cc (
  id bigint generated by default as identity,
  created_on timestamp with time zone default now(),
  primary key (id)
);

create table cc_document (
  id bigint generated by default as identity,
  cc_id bigint references cc(id) not null,
  value numeric (6,2) not null default 0,
  primary key (id)
);

create index cc_document_cc_id on cc_document (cc_id);
