create schema if not exists bank;

create table if not exists bank.client
(
    code bigint generated by default as identity primary key,
    name varchar(500) not null,
    version integer not null default 0
);

create table if not exists bank.bank_account
(
    code   bigint generated by default as identity primary key,
    number varchar(500)              not null,
    amount numeric(9, 4) default 0.0 not null,
    version integer not null default 0
);


create table if not exists bank.bank_account_client
(
    bank_account_code bigint not null references bank.bank_account,
    client_code       bigint not null references bank.client,
    primary key (bank_account_code, client_code)
);