create table board
(
    id bigserial primary key not null,
    version smallint default 0 not null,
    code varchar(10) not null,
    name varchar
);
create unique index board_code_uindex on board (code);

create table financial_document (
  id bigint generated by default as identity,
  version smallint not null default 0,
  created_on timestamp with time zone not null,
  board_id bigint not null references board,
  value decimal default 0.0 not null,

  content varchar null,
  expiration_on timestamp with time zone,

  DTYPE varchar,

  primary key (id)
);


alter table financial_document add constraint financial_document_invoice_content_not_null check (
  case
    when DTYPE = 'Invoice' then
    case
        when content is not null
          then 1
          else 0
          end
    else 1
  end = 1
);

alter table financial_document add constraint financial_document_creditnote_expiration_on_not_null check (
  case
  when DTYPE = 'CreditNote' then
    case
    when expiration_on is not null
      then 1
    else 0
    end
  else 1
  end = 1
);