create table event (
  id bigint generated by default AS IDENTITY,
  location jsonb not null,
  primary key (id)
);


create table developer (
  id bigint generated by default AS IDENTITY,
  name text not null,
  tiket jsonb,
  primary key (id)
);
