create table dashboard (
    id bigint not null generated by default as identity,
    name varchar (100),
    primary key (id)
);

create table topic (
    id bigint not null generated by default as identity,
    created_on timestamp with time zone not null,
    owner varchar(100),
    title varchar (100),
    dashboard_id bigint references dashboard (id),
    primary key (id)
);

create table post (
  id bigint references topic (id),
  content text not null,
  primary key (id)
);

create table announcement (
  id bigint references topic (id),
  valid_until date not null,
  size smallint not null default 0,
  primary key (id)
);

create table topic_statistics (
   id bigint not null generated by default as identity,
   topic_id bigint not null references topic (id),
   views integer not null default 0
);

create index topic_dashboard_id_index on topic (dashboard_id);
create unique index topic_statistics_topic_id_uindex on topic_statistics (topic_id);
alter table topic_statistics add constraint topic_statistics_topic_id_uindex unique using index topic_statistics_topic_id_uindex;

