version: "3.7"

services:
  db1:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - example-xa
    volumes:
      - .volumes/db1:/var/lib/postgresql/data

  db2:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=db2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - example-xa
    volumes:
      - .volumes/db2:/var/lib/postgresql/data

networks:
  example-xa:
    driver: bridge